### ISSUE TITLE
[blogtoblog] metadata

### ISSUE THREAD

**Issue by fkakatie** [kptdobe/helix-importer-projects#11]
**metadata available from existing blog posts**:

- description
- og:title
- og:description
- og:url
- og:image
- og:image:secure_url
- twitter:title
- twitter:description
- twitter:image

articles pre-January 2021ish don't appear to make use of the metadata table in the body of the word doc, so the description is generated server-side.

**example:**

https://blog.adobe.com/en/publish/2020/09/24/connecting-dam-dots (view source reveals telltale `...` in the description)

so when we're building the metadata table as part of the import:

- should the importer always build a row in the metadata table for description, pulling whatever text is in the `meta['description']`?
- should the importer only build a row in the metadata table for description when that description does _not_ end with `...`?
- should the importer do something else entirely?

**Comment by davidnuescheler** [comment]
i would say if the `og:title` or `og:description` or `og:image` (which will be true for all) is identical with what's in the corresponding content element (querySelectors for `h1`, `p`, `img`, i think, definitely something that @rofe should weigh in on) then don't put it into metadata table as it would just be redundant... thoughts?

**Comment by rofe** [comment]
I think comapring `og:title`s to `h1`s is straight forward, same for the hero image, but the [algo for auto-generated meta descriptions](https://github.com/adobe/helix-pages/blob/master/src/extract-metadata.js#L297-L309) is a bit convoluted... for example, we'd skip a `p` with less than 10 words in order not to accidentally get a hero caption as the description (btw, i think captions are something worth discussing in their own GH issue as I believe it was a mistake to import them as regular `p`s), and we'd cut after 25 words adding the ellipsis... I think it would be sufficient to just look for an ellipsis as identifier of auto-generated meta descriptions, as that's not likely something an author would use in the metadata block.

**Comment by rofe** [comment]
We should probably also look out for articles with `p`s inside title section, as they were used as intermediate way to define meta descriptions before we introduced the metadata block. Those would be found inside the metadata block nowadays.

**Comment by kptdobe** [comment]
FYI The logic to compute the `description` can be found here: https://github.com/adobe/helix-pages/blob/master/src/extract-metadata.js#L297-L308
